version: '3.9'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd=http://0.0.0.0:2380
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster-state=new
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - apisix-net

  apisix:
    image: apache/apisix:3.14.1-debian
    container_name: apisix
    depends_on:
      - etcd
    networks:
      - apisix-net
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080"
      - "9180:9180"

  site:
    image: httpd:2.4
    container_name: static-site
    ports:
      - "8080:80"
    volumes:
      - ./target/site:/usr/local/apache2/htdocs:ro
    restart: unless-stopped

networks:
  apisix-net:
    driver: bridge
